import Link from "next/link";
import { redirect } from "next/navigation";
import { currentUser } from "@/lib/auth";
import { getCompany } from "@/lib/store";
import { auditForCompany } from "@/lib/audit";
import { fiscalPeriodLabel } from "@/lib/mapping";
import PrintButton from "../print-button";

export default async function AuditTrail() {
  const user = await currentUser();
  if (!user) redirect("/login");
  const company = await getCompany(user!.companyId);
  const rows = await auditForCompany(company.id);

  return (
    <main className="mx-auto max-w-4xl bg-white px-8 py-10 text-slate-800">
      <div className="no-print mb-6 flex items-center justify-between">
        <Link href="/reports" className="text-sm text-brand-700 hover:underline">← Back to reports</Link>
        <PrintButton label="Download PDF" />
      </div>

      <header className="border-b-4 border-navy-900 pb-6">
        <p className="text-sm font-semibold uppercase tracking-widest text-slate-500">Audit Trail Document</p>
        <h1 className="mt-2 text-3xl font-bold text-navy-900">{company.name}</h1>
        <p className="mt-1 text-slate-500">Reporting period: {fiscalPeriodLabel(company)} · {rows.length} logged changes</p>
        <p className="mt-2 text-xs text-slate-400">
          Append-only log: every data change is recorded with its previous value, new value, the user who made it,
          the emission factor applied, and the calculation performed. Nothing is ever overwritten.
        </p>
      </header>

      <table className="mt-6 w-full text-xs">
        <thead>
          <tr className="border-b-2 border-slate-300 text-left uppercase tracking-wide text-slate-400">
            <th className="pb-2 pr-3">Timestamp</th>
            <th className="pb-2 pr-3">User</th>
            <th className="pb-2 pr-3">Section</th>
            <th className="pb-2 pr-3">Field</th>
            <th className="pb-2 pr-3">Previous</th>
            <th className="pb-2">New value</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.id} className="border-b border-slate-100 align-top">
              <td className="py-2 pr-3 whitespace-nowrap text-slate-400">{new Date(r.ts).toLocaleString()}</td>
              <td className="py-2 pr-3">{r.userName}</td>
              <td className="py-2 pr-3 capitalize">{r.section}</td>
              <td className="py-2 pr-3 font-medium">{r.field}</td>
              <td className="py-2 pr-3 text-slate-400">{r.prev}</td>
              <td className="py-2 font-medium">{r.next}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <section className="mt-8">
        <h2 className="text-lg font-bold text-navy-900">Current Calculations on Record</h2>
        <table className="mt-3 w-full text-xs">
          <thead>
            <tr className="border-b-2 border-slate-300 text-left uppercase tracking-wide text-slate-400">
              <th className="pb-2 pr-3">Category</th>
              <th className="pb-2">Calculation performed</th>
            </tr>
          </thead>
          <tbody>
            {company.calcs.map((c) => (
              <tr key={c.id} className="border-b border-slate-100 align-top">
                <td className="py-2 pr-3 font-medium whitespace-nowrap">{c.category}</td>
                <td className="py-2 text-slate-500">{c.formula}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <footer className="mt-10 border-t border-slate-200 pt-4 text-xs text-slate-400">
        {company.name} — Audit Trail — generated by GreenTrack on {new Date().toLocaleDateString()}.
      </footer>
    </main>
  );
}
