import Link from "next/link";
import { redirect } from "next/navigation";
import { currentUser } from "@/lib/auth";
import { loadCompany } from "@/lib/store";
import { auditForCompany } from "@/lib/audit";
import { fiscalPeriodLabel } from "@/lib/mapping";
import PrintButton from "../print-button";

export default async function AuditTrail() {
  const user = await currentUser();
  if (!user) redirect("/login");
  const company = await loadCompany(user.companyId);
  const rows = await auditForCompany(company.id);

  return (
    <main className="mx-auto max-w-4xl px-8 py-10" style={{ background: "#fff", color: "var(--text)" }}>
      <div className="no-print mb-6 flex items-center justify-between">
        <Link href="/reports" className="text-sm font-medium hover:opacity-70" style={{ color: "var(--primary)" }}>
          ← Back to reports
        </Link>
        <PrintButton label="Download PDF" />
      </div>

      <header className="pb-6" style={{ borderBottom: `4px solid var(--text)` }}>
        <p className="text-sm font-semibold uppercase tracking-widest" style={{ color: "var(--text-muted)" }}>
          Audit Trail Document
        </p>
        <h1 className="mt-2 text-3xl font-bold font-display" style={{ color: "var(--text)" }}>{company.name}</h1>
        <p className="mt-1 text-sm" style={{ color: "var(--text-muted)" }}>
          Reporting period: {fiscalPeriodLabel(company)} · {rows.length} logged changes
        </p>
        <p className="mt-2 text-xs" style={{ color: "var(--text-muted)" }}>
          Append-only log: every data change is recorded with its previous value, new value, the user who made it,
          the emission factor applied, and the calculation performed. Nothing is ever overwritten.
        </p>
      </header>

      <table className="mt-6 w-full text-xs">
        <thead>
          <tr className="text-left uppercase tracking-wide" style={{ borderBottom: "2px solid var(--divider)", color: "var(--text-muted)" }}>
            <th className="pb-2 pr-3">Timestamp</th>
            <th className="pb-2 pr-3">User</th>
            <th className="pb-2 pr-3">Section</th>
            <th className="pb-2 pr-3">Field</th>
            <th className="pb-2 pr-3">Previous</th>
            <th className="pb-2">New value</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.id} className="align-top" style={{ borderBottom: "1px solid var(--divider)" }}>
              <td className="py-2 pr-3 whitespace-nowrap" style={{ color: "var(--text-muted)" }}>{new Date(r.ts).toLocaleString()}</td>
              <td className="py-2 pr-3">{r.userName}</td>
              <td className="py-2 pr-3 capitalize">{r.section}</td>
              <td className="py-2 pr-3 font-medium">{r.field}</td>
              <td className="py-2 pr-3" style={{ color: "var(--text-muted)" }}>{r.prev}</td>
              <td className="py-2 font-medium">{r.next}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <section className="mt-8">
        <h2 className="text-lg font-bold font-display" style={{ color: "var(--text)" }}>Current Calculations on Record</h2>
        <table className="mt-3 w-full text-xs">
          <thead>
            <tr className="text-left uppercase tracking-wide" style={{ borderBottom: "2px solid var(--divider)", color: "var(--text-muted)" }}>
              <th className="pb-2 pr-3">Category</th>
              <th className="pb-2">Calculation performed</th>
            </tr>
          </thead>
          <tbody>
            {company.calcs.map((c) => (
              <tr key={c.id} className="align-top" style={{ borderBottom: "1px solid var(--divider)" }}>
                <td className="py-2 pr-3 font-medium whitespace-nowrap">{c.category}</td>
                <td className="py-2" style={{ color: "var(--text-muted)" }}>{c.formula}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <footer className="mt-10 pt-4 text-xs" style={{ borderTop: "1px solid var(--divider)", color: "var(--text-muted)" }}>
        {company.name} — Audit Trail — generated by GreenTrack on {new Date().toLocaleDateString()}.
      </footer>
    </main>
  );
}
