import Link from "next/link";
import { Logo } from "@/components/ui";

export default function TermsPage() {
  return (
    <main style={{ background: "var(--bg)", minHeight: "100vh" }}>
      <header
        className="flex items-center justify-between px-8 py-5"
        style={{ background: "var(--surface)", borderBottom: "1px solid var(--divider)" }}
      >
        <Link href="/"><Logo /></Link>
      </header>
      <article className="mx-auto max-w-3xl px-6 py-16 prose" style={{ color: "var(--text)" }}>
        <h1 className="text-3xl font-black font-display" style={{ color: "var(--text)" }}>Terms of Service</h1>
        <p className="mt-2 text-sm" style={{ color: "var(--text-muted)" }}>Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="mt-8 rounded-xl p-6" style={{ background: "var(--warning-tint)", border: "1px solid var(--warning)" }}>
          <p className="text-sm font-semibold" style={{ color: "var(--warning)" }}>Draft — legal review pending</p>
          <p className="mt-1 text-sm" style={{ color: "var(--warning)" }}>
            This page is a placeholder. Full terms of service are being drafted and will be published before general availability.
            Contact <a href="mailto:hello@sendrow.app" style={{ color: "var(--warning)" }}>hello@sendrow.app</a> with questions.
          </p>
        </div>

        <h2 className="mt-10 text-xl font-bold font-display" style={{ color: "var(--text)" }}>1. Agreement to Terms</h2>
        <p style={{ color: "var(--text-muted)" }}>
          By accessing or using Sendrow ("Service"), you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the Service.
        </p>

        <h2 className="mt-8 text-xl font-bold font-display" style={{ color: "var(--text)" }}>2. Use of the Service</h2>
        <p style={{ color: "var(--text-muted)" }}>
          Sendrow provides tools for GHG emissions inventory, reporting, and ESG data management. You are responsible for the accuracy of data you enter. Sendrow does not verify the accuracy of emissions data submitted by users.
        </p>

        <h2 className="mt-8 text-xl font-bold font-display" style={{ color: "var(--text)" }}>3. Data and Privacy</h2>
        <p style={{ color: "var(--text-muted)" }}>
          Your data is governed by our <Link href="/privacy" style={{ color: "var(--primary)" }}>Privacy Policy</Link>. We do not sell your data to third parties.
        </p>

        <h2 className="mt-8 text-xl font-bold font-display" style={{ color: "var(--text)" }}>4. Limitation of Liability</h2>
        <p style={{ color: "var(--text-muted)" }}>
          Sendrow is provided "as is." We make no warranties regarding accuracy of emission factor data or regulatory compliance of outputs generated by the Service.
        </p>

        <h2 className="mt-8 text-xl font-bold font-display" style={{ color: "var(--text)" }}>5. Contact</h2>
        <p style={{ color: "var(--text-muted)" }}>
          Questions about these terms? Email <a href="mailto:hello@sendrow.app" style={{ color: "var(--primary)" }}>hello@sendrow.app</a>.
        </p>
      </article>
    </main>
  );
}
